# Generated by Django 6.0.6 on 2026-06-30 17:50

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('latitude', models.FloatField(help_text='Latitude coordinate for map focus pointer marker')),
                ('longitude', models.FloatField(help_text='Longitude coordinate for map focus pointer marker')),
                ('radius_multiplier', models.FloatField(default=1.0, help_text='Multiplier radius dimension sizing map circle')),
                ('hex_color', models.CharField(default='#F57C00', help_text='Hex color string indicator layout polygon', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('heading_text', models.CharField(help_text='Use HTML tags like <span> for highlights', max_length=255)),
                ('subheading_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMetricTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Bootstrap icon class string name, e.g., bi-wifi', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('metric_value', models.CharField(help_text='E.g., 95% of Nairobi', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_address', models.CharField(max_length=255)),
                ('new_address', models.CharField(max_length=255)),
                ('preferred_move_date', models.DateField()),
                ('contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Format: +254700000000', regex='^\\+?1?\\d{9,15}$')])),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(help_text='Upload site logo', max_length=255, verbose_name='image')),
                ('company_name', models.CharField(default='ZooKonnect', max_length=100)),
                ('phone_number', models.CharField(default='+254 700 000 000', max_length=20)),
                ('email_address', models.EmailField(default='support@ZooKonnect.co.ke', max_length=254)),
                ('office_address', models.CharField(default='Nairobi, Kenya', max_length=255)),
                ('whatsapp_url', models.URLField(default='https://wa.me/254700000000')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description tag')),
                ('og_image', cloudinary.models.CloudinaryField(blank=True, help_text='Open Graph image tag', max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
