# Generated by Django 6.0.6 on 2026-06-30 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='about/')),
                ('heading_text', models.CharField(default="About <span class='highlight'>ZooKonnect</span>", max_length=255)),
                ('subheading_text', models.TextField(default="We're on a mission to connect Kenya with fast, reliable, and affordable internet.")),
            ],
            options={
                'verbose_name': 'About Page Hero',
                'verbose_name_plural': 'About Page Hero',
            },
        ),
        migrations.CreateModel(
            name='AboutStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Our Story', max_length=50)),
                ('heading', models.CharField(default='Connecting Kenya Since 2020', max_length=255)),
                ('content', models.TextField()),
                ('stat1_number', models.CharField(default='5+', max_length=20)),
                ('stat1_label', models.CharField(default='Cities Covered', max_length=50)),
                ('stat2_number', models.CharField(default='2,000+', max_length=20)),
                ('stat2_label', models.CharField(default='Happy Customers', max_length=50)),
                ('stat3_number', models.CharField(default='99.9%', max_length=20)),
                ('stat3_label', models.CharField(default='Uptime Guarantee', max_length=50)),
            ],
            options={
                'verbose_name': 'About Story Section',
                'verbose_name_plural': 'About Story Section',
            },
        ),
        migrations.CreateModel(
            name='CompanyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='bi-rocket-takeoff', help_text='Bootstrap icon class name', max_length=50)),
                ('year_title', models.CharField(default='2020 — Launched in Nairobi', help_text='E.g., 2020 — Launched in Nairobi', max_length=100)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Company Milestone',
                'verbose_name_plural': 'Company Milestones',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Format: +254700000000', regex='^\\+?1?\\d{9,15}$')])),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('sales', 'Sales / New Connection'), ('support', 'Technical Support'), ('billing', 'Billing / Payments'), ('relocation', 'Relocation Request'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='bi-wifi', help_text='Bootstrap icon class name', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Choose Reason',
                'verbose_name_plural': 'Why Choose Reasons',
                'ordering': ['sort_order'],
            },
        ),
    ]
