# Generated by Django 6.0.6 on 2026-06-30 18:37

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_aboutpagehero_aboutstorysection_companymilestone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', cloudinary.models.CloudinaryField(help_text='Hero background image', max_length=255, verbose_name='image')),
                ('title', models.CharField(default='About Us', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text="e.g. We're on a mission...", max_length=200)),
                ('breadcrumb_home', models.CharField(default='Home', max_length=50)),
                ('breadcrumb_separator', models.CharField(default=' / ', max_length=10)),
                ('breadcrumb_current', models.CharField(default='About', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Hero',
                'verbose_name_plural': 'About Heroes',
            },
        ),
        migrations.CreateModel(
            name='AboutMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-rocket-takeoff', help_text='Bootstrap icon class, e.g. bi-rocket-takeoff', max_length=50)),
                ('year', models.CharField(help_text='e.g. 2020', max_length=20)),
                ('title', models.CharField(help_text='e.g. Launched in Nairobi', max_length=100)),
                ('description', models.CharField(help_text='e.g. Started with 100 customers.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 5+', max_length=20)),
                ('label', models.CharField(help_text='e.g. Cities Covered', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Our Story', max_length=50)),
                ('title', models.CharField(help_text='e.g. Connecting Kenya Since 2020', max_length=200)),
                ('description', models.TextField(help_text='The main story paragraph.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Story',
                'verbose_name_plural': 'About Stories',
            },
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bi-wifi', 'Wi‑Fi'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-rocket', 'Rocket'), ('bi-globe', 'Globe')], default='bi-wifi', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='AboutPageHero',
        ),
        migrations.DeleteModel(
            name='AboutStorySection',
        ),
        migrations.DeleteModel(
            name='CompanyMilestone',
        ),
        migrations.DeleteModel(
            name='WhyChooseReason',
        ),
        migrations.AddField(
            model_name='aboutstat',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='zoo.aboutstory'),
        ),
        migrations.AddField(
            model_name='aboutmilestone',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='zoo.aboutstory'),
        ),
    ]
