# Generated by Django 6.0.6 on 2026-06-30 18:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_abouthero_aboutmilestone_aboutstat_aboutstory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Ready to Get Connected?', max_length=200)),
                ('subtitle', models.TextField(help_text='e.g. Join thousands...')),
                ('button_text', models.CharField(default='Sign Up Now', max_length=50)),
                ('button_url', models.CharField(default='/contact/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Call to Action',
                'verbose_name_plural': 'Call to Actions',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bi-speedometer2', 'Speedometer'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-wifi', 'Wi‑Fi'), ('bi-arrow-repeat', 'Arrow Repeat'), ('bi-rocket', 'Rocket')], default='bi-speedometer2', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home', 'Home'), ('business', 'Business')], default='home', max_length=20)),
                ('name', models.CharField(help_text='e.g. Starter, Pro', max_length=50)),
                ('speed', models.CharField(help_text='e.g. Up to 20 Mbps', max_length=50)),
                ('price', models.CharField(help_text='e.g. KES 2,500', max_length=50)),
                ('price_period', models.CharField(default='/mo', help_text='e.g. /mo, /yr', max_length=20)),
                ('description', models.CharField(help_text='Short description', max_length=200)),
                ('features', models.TextField(help_text='Comma-separated list of features')),
                ('is_popular', models.BooleanField(default=False)),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('button_url', models.CharField(default='/contact/', help_text='e.g. /contact/ or /signup/', max_length=200)),
                ('button_style', models.CharField(choices=[('primary', 'Primary'), ('outline', 'Outline')], default='primary', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bi-wifi', 'Wi‑Fi'), ('bi-building', 'Building'), ('bi-house-door', 'House'), ('bi-globe', 'Globe')], default='bi-wifi', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag_text', models.CharField(help_text='e.g. Up to 1 Gbps', max_length=50)),
                ('tag_style', models.CharField(choices=[('orange', 'Orange'), ('gold', 'Gold'), ('green', 'Green')], default='orange', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(default='Our Services', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Fast, reliable internet for every need...', max_length=200)),
                ('breadcrumb_home', models.CharField(default='Home', max_length=50)),
                ('breadcrumb_separator', models.CharField(default=' / ', max_length=10)),
                ('breadcrumb_current', models.CharField(default='Services', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services Hero',
                'verbose_name_plural': 'Services Heroes',
            },
        ),
    ]
