# Generated by Django 6.0.6 on 2026-06-30 19:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_cta_feature_plan_service_serviceshero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmilestone',
            options={'ordering': ['order'], 'verbose_name': 'About Milestone', 'verbose_name_plural': 'About Milestones'},
        ),
        migrations.AlterModelOptions(
            name='aboutstat',
            options={'ordering': ['order'], 'verbose_name': 'About Stat', 'verbose_name_plural': 'About Stats'},
        ),
        migrations.AlterModelOptions(
            name='whychoose',
            options={'ordering': ['order'], 'verbose_name': 'Why Choose Us Item', 'verbose_name_plural': 'Why Choose Us Items'},
        ),
        migrations.RemoveField(
            model_name='abouthero',
            name='title',
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='background_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Subtitle below the main heading (e.g. 'We're on a mission...')", max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='description',
            field=models.CharField(help_text="e.g. 'Started with 100 customers.'", max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='icon',
            field=models.CharField(choices=[('bi-wifi', 'Wi-Fi'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-rocket-takeoff', 'Rocket Takeoff'), ('bi-map', 'Map'), ('bi-phone', 'Phone'), ('bi-people', 'People'), ('bi-trophy', 'Trophy'), ('bi-lightning-fill', 'Lightning'), ('bi-building', 'Building'), ('bi-house-door', 'House'), ('bi-globe', 'Globe'), ('bi-speedometer2', 'Speedometer'), ('bi-arrow-repeat', 'Arrow Repeat'), ('bi-info-circle', 'Info Circle'), ('bi-dot', 'Dot')], default='bi-rocket-takeoff', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='title',
            field=models.CharField(help_text="e.g. 'Launched in Nairobi'", max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='year',
            field=models.CharField(help_text="e.g. '2020'", max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='label',
            field=models.CharField(help_text="e.g. 'Cities Covered'", max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='number',
            field=models.CharField(help_text="e.g. '5+'", max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutstory',
            name='badge_text',
            field=models.CharField(default='Our Story', help_text="Text inside the badge (e.g. 'Our Story')", max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutstory',
            name='title',
            field=models.CharField(help_text="Main heading (e.g. 'Connecting Kenya Since 2020')", max_length=200),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='icon',
            field=models.CharField(choices=[('bi-wifi', 'Wi-Fi'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-rocket-takeoff', 'Rocket Takeoff'), ('bi-map', 'Map'), ('bi-phone', 'Phone'), ('bi-people', 'People'), ('bi-trophy', 'Trophy'), ('bi-lightning-fill', 'Lightning'), ('bi-building', 'Building'), ('bi-house-door', 'House'), ('bi-globe', 'Globe'), ('bi-speedometer2', 'Speedometer'), ('bi-arrow-repeat', 'Arrow Repeat'), ('bi-info-circle', 'Info Circle'), ('bi-dot', 'Dot')], default='bi-wifi', max_length=50),
        ),
    ]
