# Generated by Django 6.0.6 on 2026-06-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_alter_aboutmilestone_options_alter_aboutstat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutstory',
            name='badge_text',
        ),
    ]
