# Generated by Django 6.0.6 on 2026-06-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_remove_aboutstory_badge_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceshero',
            name='title',
        ),
        migrations.AlterField(
            model_name='cta',
            name='subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cta',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(choices=[('bi-wifi', 'Wi-Fi'), ('bi-building', 'Building'), ('bi-house-door', 'House'), ('bi-speedometer2', 'Speedometer'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-arrow-repeat', 'Arrow Repeat'), ('bi-rocket-takeoff', 'Rocket'), ('bi-globe', 'Globe'), ('bi-check-circle-fill', 'Check Circle')], default='bi-speedometer2', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='button_url',
            field=models.CharField(default='/contact/', max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_period',
            field=models.CharField(default='/mo', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('bi-wifi', 'Wi-Fi'), ('bi-building', 'Building'), ('bi-house-door', 'House'), ('bi-speedometer2', 'Speedometer'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-arrow-repeat', 'Arrow Repeat'), ('bi-rocket-takeoff', 'Rocket'), ('bi-globe', 'Globe'), ('bi-check-circle-fill', 'Check Circle')], default='bi-wifi', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceshero',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle below the main heading', max_length=200),
        ),
    ]
