# Generated by Django 6.0.6 on 2026-06-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_remove_serviceshero_title_alter_cta_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cta',
            options={'verbose_name': 'Call to Action'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['category', 'order']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='serviceshero',
            options={'verbose_name': 'Services Hero'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.TextField(help_text='Comma-separated list'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='speed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='tag_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceshero',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
