# Generated by Django 6.0.6 on 2026-07-27 08:06

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_alter_cta_options_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cta',
            options={'verbose_name': 'Call to Action', 'verbose_name_plural': 'Calls to Action'},
        ),
        migrations.AlterModelOptions(
            name='serviceshero',
            options={'verbose_name': 'Services Hero', 'verbose_name_plural': 'Services Heroes'},
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='breadcrumb_current',
            field=models.CharField(blank=True, default='About', max_length=50),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='breadcrumb_home',
            field=models.CharField(blank=True, default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='breadcrumb_separator',
            field=models.CharField(blank=True, default=' / ', max_length=10),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle below the main heading', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='description',
            field=models.CharField(blank=True, help_text="e.g. 'Started with 100 customers.'", max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='icon',
            field=models.CharField(blank=True, choices=[('bi-wifi', 'Wi-Fi'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-rocket-takeoff', 'Rocket Takeoff'), ('bi-map', 'Map'), ('bi-phone', 'Phone'), ('bi-people', 'People'), ('bi-trophy', 'Trophy'), ('bi-lightning-fill', 'Lightning'), ('bi-building', 'Building'), ('bi-house-door', 'House'), ('bi-globe', 'Globe'), ('bi-speedometer2', 'Speedometer'), ('bi-arrow-repeat', 'Arrow Repeat'), ('bi-info-circle', 'Info Circle'), ('bi-dot', 'Dot'), ('bi-check-circle-fill', 'Check Circle')], default='bi-rocket-takeoff', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='zoo.aboutstory'),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='title',
            field=models.CharField(blank=True, help_text="e.g. 'Launched in Nairobi'", max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutmilestone',
            name='year',
            field=models.CharField(blank=True, help_text="e.g. '2020'", max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='label',
            field=models.CharField(blank=True, help_text="e.g. 'Cities Covered'", max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='number',
            field=models.CharField(blank=True, help_text="e.g. '5+'", max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='zoo.aboutstory'),
        ),
        migrations.AlterField(
            model_name='aboutstory',
            name='description',
            field=models.TextField(blank=True, help_text='The main story paragraph.'),
        ),
        migrations.AlterField(
            model_name='aboutstory',
            name='title',
            field=models.CharField(blank=True, help_text='Main heading', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Format: +254700000000', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, choices=[('general', 'General Inquiry'), ('sales', 'Sales / New Connection'), ('support', 'Technical Support'), ('billing', 'Billing / Payments'), ('relocation', 'Relocation Request'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='coveragearea',
            name='city_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coveragearea',
            name='hex_color',
            field=models.CharField(blank=True, default='#F57C00', help_text='Hex color string indicator layout polygon', max_length=7),
        ),
        migrations.AlterField(
            model_name='coveragearea',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='coveragearea',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate for map focus pointer marker', null=True),
        ),
        migrations.AlterField(
            model_name='coveragearea',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate for map focus pointer marker', null=True),
        ),
        migrations.AlterField(
            model_name='coveragearea',
            name='radius_multiplier',
            field=models.FloatField(blank=True, default=1.0, help_text='Multiplier radius dimension sizing map circle', null=True),
        ),
        migrations.AlterField(
            model_name='cta',
            name='button_text',
            field=models.CharField(blank=True, default='Sign Up Now', max_length=50),
        ),
        migrations.AlterField(
            model_name='cta',
            name='button_url',
            field=models.CharField(blank=True, default='/contact/', max_length=200),
        ),
        migrations.AlterField(
            model_name='cta',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cta',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, choices=[('bi-wifi', 'Wi-Fi'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-rocket-takeoff', 'Rocket Takeoff'), ('bi-map', 'Map'), ('bi-phone', 'Phone'), ('bi-people', 'People'), ('bi-trophy', 'Trophy'), ('bi-lightning-fill', 'Lightning'), ('bi-building', 'Building'), ('bi-house-door', 'House'), ('bi-globe', 'Globe'), ('bi-speedometer2', 'Speedometer'), ('bi-arrow-repeat', 'Arrow Repeat'), ('bi-info-circle', 'Info Circle'), ('bi-dot', 'Dot'), ('bi-check-circle-fill', 'Check Circle')], default='bi-speedometer2', max_length=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='heading_text',
            field=models.CharField(blank=True, help_text='Use HTML tags like <span> for highlights', max_length=255),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subheading_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='networkmetrictile',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Bootstrap icon class string name, e.g., bi-wifi', max_length=50),
        ),
        migrations.AlterField(
            model_name='networkmetrictile',
            name='metric_value',
            field=models.CharField(blank=True, help_text='E.g., 95% of Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkmetrictile',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='button_style',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('outline', 'Outline')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='button_text',
            field=models.CharField(blank=True, default='Get Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='button_url',
            field=models.CharField(blank=True, default='/contact/', max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('business', 'Business')], default='home', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated list'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_period',
            field=models.CharField(blank=True, default='/mo', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='speed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='relocationrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Format: +254700000000', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='relocationrequest',
            name='current_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='relocationrequest',
            name='new_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='relocationrequest',
            name='preferred_move_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, choices=[('bi-wifi', 'Wi-Fi'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-rocket-takeoff', 'Rocket Takeoff'), ('bi-map', 'Map'), ('bi-phone', 'Phone'), ('bi-people', 'People'), ('bi-trophy', 'Trophy'), ('bi-lightning-fill', 'Lightning'), ('bi-building', 'Building'), ('bi-house-door', 'House'), ('bi-globe', 'Globe'), ('bi-speedometer2', 'Speedometer'), ('bi-arrow-repeat', 'Arrow Repeat'), ('bi-info-circle', 'Info Circle'), ('bi-dot', 'Dot'), ('bi-check-circle-fill', 'Check Circle')], default='bi-wifi', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='tag_style',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('gold', 'Gold'), ('green', 'Green')], default='orange', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='tag_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceshero',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='serviceshero',
            name='breadcrumb_current',
            field=models.CharField(blank=True, default='Services', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceshero',
            name='breadcrumb_home',
            field=models.CharField(blank=True, default='Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceshero',
            name='breadcrumb_separator',
            field=models.CharField(blank=True, default=' / ', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='company_name',
            field=models.CharField(blank=True, default='ZooKonnect', max_length=150),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_address',
            field=models.EmailField(blank=True, default='support@ZooKonnect.co.ke', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload site logo', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='office_address',
            field=models.CharField(blank=True, default='Nairobi, Kenya', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone_number',
            field=models.CharField(blank=True, default='+254 700 000 000', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='https://wa.me/254700000000'),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='icon',
            field=models.CharField(blank=True, choices=[('bi-wifi', 'Wi-Fi'), ('bi-shield-check', 'Shield Check'), ('bi-headset', 'Headset'), ('bi-coin', 'Coin'), ('bi-rocket-takeoff', 'Rocket Takeoff'), ('bi-map', 'Map'), ('bi-phone', 'Phone'), ('bi-people', 'People'), ('bi-trophy', 'Trophy'), ('bi-lightning-fill', 'Lightning'), ('bi-building', 'Building'), ('bi-house-door', 'House'), ('bi-globe', 'Globe'), ('bi-speedometer2', 'Speedometer'), ('bi-arrow-repeat', 'Arrow Repeat'), ('bi-info-circle', 'Info Circle'), ('bi-dot', 'Dot'), ('bi-check-circle-fill', 'Check Circle')], default='bi-wifi', max_length=50),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='whychoose',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
